apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: eval
     name: mysql-mysql-0
  hostPath:
    path: "/home/ubuntu/eval/data"