apiVersion: v1
kind: Secret
metadata:
  name: mysql-user
  namespace: eval
type: Opaque
stringData:
  mysql-user: "jcaillabet"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
  namespace: eval
type: Opaque
stringData:
  mysql-password: "Pass12357*$"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-host
  namespace: eval
type: Opaque
stringData:
  mysql-host: "mysql"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-database
  namespace: eval
type: Opaque
stringData:
  mysql-database: "jcaillabet"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-port
  namespace: eval
type: Opaque
stringData:
  mysql-port: "3307"